openapi: 3.0.3
info:
  title: Customers Companies
  contact:
    name: API Support
    url: https://eniak.ru/contacts
    email: eniak@info.ru
  version: 1.0.0
  description: Customers Company
servers:
  - url: /api/v1
tags:
  - name: companies
    description: Компания покупателя
  - name: company_employees
    description: Сотрудники компании
paths:
  /companies:search:
    $ref: './companies/path.yaml#/SearchCompany'
  /companies:
    $ref: './companies/path.yaml#/CreateCompany'
  /companies/{id}:
    $ref: './companies/path.yaml#/CurrentCompany'

  /companies/employees:search:
    $ref: './companies/path.yaml#/SearchCompanyEmployees'
  /companies/employees:
    $ref: './companies/path.yaml#/CompanyEmployee'
  /companies/employees/{id}:
    $ref: './companies/path.yaml#/CurrentCompanyEmployee'

  /companies/employee-balances:search:
    $ref: './companies/path.yaml#/SearchEmployeeBalances'

components:
  parameters:
    QueryInclude:
      $ref: './common_parameters.yaml#/QueryInclude'
    PathId:
      $ref: './common_parameters.yaml#/PathId'
  schemas:
    EmptyDataResponse:
      type: object
      properties:
        data:
          type: object
          nullable: true
        meta:
          type: object
      required:
        - data
    PaginationTypeEnum:
      $ref: './common_schemas.yaml#/PaginationTypeEnum'
    CompanyStatusEnum:
      $ref: './companies/enums/company_status_enum.yaml'
    CompanyEmployeeStatusEnum:
      $ref: './companies/enums/company_employee_status_enum.yaml'
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
