<?php

return [
    // The URL where the OpenAPI documentation will be accessible
    'api_docs_url' => public_path('api/v1/index.yaml'),

    /**
     * The entities for which code generation will be performed.
     * You can specify which entities should be generated by adding them to this array.
     * Supported entities:
     * - 'route': Generate Laravel routes based on OpenAPI paths.
     * - 'request': Generate request classes based on OpenAPI request bodies.
     * - 'resource': Generate resource classes for API responses.
     * - 'controller': Generate controllers for handling API requests.
     * By default, all supported entities will be generated.
     * To exclude specific entities, simply remove them from this array.
     */
    'entities' => [
        'route',
        'request',
        'resource',
        'controller',
    ],

    // Additional paths used in the application
    'paths' => [
        // The file path where the OpenAPI routes will be generated
        'routes_file' => base_path('routes/openapi-codegen.php'),
    ],
];
