name: run-tests

on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/run-tests.yaml'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'composer.lock'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - uses: php-actions/composer@v6
      - run: echo "Composer dependencies have been installed"
      - run: cp -r ./tests/v1 ./vendor/orchestra/testbench-core/laravel/public
      - run: ls ./vendor/orchestra/testbench-core/laravel/public
      - uses: php-actions/phpunit@v3
        with:
          configuration: ./phpunit.xml.dist
          php_version: 8.0